services:
  dynamodb:
    image: amazon/dynamodb-local
    expose:
      - 8000
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - 8001:8001