"""added data_source schema field

Revision ID: 02a205967eb3
Revises: a2389fbbba99
Create Date: 2025-07-30 17:30:05.902096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02a205967eb3'
down_revision: Union[str, Sequence[str], None] = 'a2389fbbba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataSource', sa.Column('data_source_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataSource', 'data_source_schema')
    # ### end Alembic commands ###
