"""modified datasource table

Revision ID: 17caea9e36ab
Revises: 3c2086017d2b
Create Date: 2025-07-21 20:31:05.237482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17caea9e36ab'
down_revision: Union[str, Sequence[str], None] = '3c2086017d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DataSource_data_source_user_id'), table_name='DataSource')
    op.create_index(op.f('ix_DataSource_data_source_user_id'), 'DataSource', ['data_source_user_id'], unique=False)
    op.create_unique_constraint(None, 'DataSource', ['data_source_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DataSource', type_='unique')
    op.drop_index(op.f('ix_DataSource_data_source_user_id'), table_name='DataSource')
    op.create_index(op.f('ix_DataSource_data_source_user_id'), 'DataSource', ['data_source_user_id'], unique=True)
    # ### end Alembic commands ###
