"""added data source model

Revision ID: 3c2086017d2b
Revises: ced10486bd0b
Create Date: 2025-07-21 16:51:09.192118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c2086017d2b'
down_revision: Union[str, Sequence[str], None] = 'ced10486bd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataSource',
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('data_source_user_id', sa.Integer(), nullable=False),
    sa.Column('data_source_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('data_source_type', sa.Enum('CSV', 'XLSX', 'GOOGLE', 'PDF', 'POSTGRES', 'MYSQL', 'MSSQL', 'ORACLE', 'NOSQL', name='datasourcetype'), nullable=False),
    sa.Column('data_source_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('data_source_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_source_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_source_id')
    )
    op.create_index(op.f('ix_DataSource_data_source_user_id'), 'DataSource', ['data_source_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DataSource_data_source_user_id'), table_name='DataSource')
    op.drop_table('DataSource')
    # ### end Alembic commands ###
