"""modified datasource table

Revision ID: 7e9319b923f3
Revises: 17caea9e36ab
Create Date: 2025-07-21 20:38:19.833515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e9319b923f3'
down_revision: Union[str, Sequence[str], None] = '17caea9e36ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('DataSource_data_source_name_key'), 'DataSource', type_='unique')
    op.create_unique_constraint('unique_user_data_source_name', 'DataSource', ['data_source_user_id', 'data_source_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_data_source_name', 'DataSource', type_='unique')
    op.create_unique_constraint(op.f('DataSource_data_source_name_key'), 'DataSource', ['data_source_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
