"""updated data source table

Revision ID: a2389fbbba99
Revises: 99ecb6a3f0d7
Create Date: 2025-07-30 05:09:20.025550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2389fbbba99'
down_revision: Union[str, Sequence[str], None] = '99ecb6a3f0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataSource', sa.Column('data_source_is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'DataSource', ['data_source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DataSource', type_='unique')
    op.drop_column('DataSource', 'data_source_is_active')
    # ### end Alembic commands ###
