"""modified data source table

Revision ID: c7cdc50bc99b
Revises: 02a205967eb3
Create Date: 2025-08-12 16:03:13.058959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7cdc50bc99b'
down_revision: Union[str, Sequence[str], None] = '02a205967eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('DataSource_data_source_url_key'), 'DataSource', type_='unique')
    op.create_unique_constraint('unique_user_data_source_url', 'DataSource', ['data_source_user_id', 'data_source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_data_source_url', 'DataSource', type_='unique')
    op.create_unique_constraint(op.f('DataSource_data_source_url_key'), 'DataSource', ['data_source_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
