"""init migration

Revision ID: ced10486bd0b
Revises: 
Create Date: 2025-07-21 13:30:16.658659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ced10486bd0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_user_email'), 'User', ['user_email'], unique=True)
    op.create_table('UserProfile',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_user_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_profile_avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_phone_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_profile_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_profile_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_profile_id')
    )
    op.create_index(op.f('ix_UserProfile_user_profile_user_id'), 'UserProfile', ['user_profile_user_id'], unique=True)
    op.create_table('UserSocialConnection',
    sa.Column('social_id', sa.Integer(), nullable=False),
    sa.Column('social_user_id', sa.Integer(), nullable=False),
    sa.Column('social_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_expires_at', sa.DateTime(), nullable=True),
    sa.Column('social_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('social_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['social_user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('social_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSocialConnection')
    op.drop_index(op.f('ix_UserProfile_user_profile_user_id'), table_name='UserProfile')
    op.drop_table('UserProfile')
    op.drop_index(op.f('ix_User_user_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
