"""modified data source table

Revision ID: ec3ddc14fc43
Revises: c7cdc50bc99b
Create Date: 2025-08-12 22:45:54.155668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec3ddc14fc43'
down_revision: Union[str, Sequence[str], None] = 'c7cdc50bc99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_user_data_source_url'), 'DataSource', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_user_data_source_url'), 'DataSource', ['data_source_user_id', 'data_source_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
