name: CI/CD for Lambda Deployment

on:
  push:
    branches:
      - prod

env:
  IMAGE_TAG: latest

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Log in to Amazon ECR using AWS CLI
      run: |
        aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

    - name: Build Docker image
      run: |
        # Build the Docker image without pushing it
        docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY_NAME }} ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
    
    - name: Deploy Docker image to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --image-uri ${{ secrets.ECR_IMAGE_URI }} \
          --region ${{ secrets.REGION }}
